// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhwllbjimcvmgnpgvydd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZod2xsYmppbWN2bWducGd2eWRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MDU2NDksImV4cCI6MjA2MjE4MTY0OX0.uaj6kyCYow_LU-pg4hueQ-qLeQ377SGRR0gs8UFHrlY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);